# app3/app.yml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monorepo-demo-app3
  labels:
    project: monorepo-demo
    role: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      project: monorepo-demo
      role: app3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: monorepo-demo-app3
      labels:
        project: monorepo-demo
        role: app3
    annotations:
      samson/dockerfile: app3/Dockerfile
    spec:
      containers:
      - name: monorepo-demo
        image: my.registry/some-namespace/monorepo-demo-app3:latest
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
          limits:
            cpu: 100m
            memory: 75Mi
        ports:
        - name: main-port
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: monorepo-demo
  labels:
    project: monorepo-demo
    role: app3
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: main-port
  selector:
    project: monorepo-demo
    role: app3
